baseURL = "https://seanobrien.art"
languageCode = "en-us"
title = "Sean O'Brien Paintings & Illustrations"

# Novela settings
theme = "novela"

DefaultContentLanguage = "en"
paginate = 6
publishDir = "docs"

[social]
github= "https://github.com/seans-art"
instagram = "https://www.instagram.com/seanosmo/"

[taxonomies]
author = "authors"

[tracking]
googleTagManager = "GTM-PXPCG24"